### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by adamtherookie**

### CODE REVIEW

**Review by DamieFC — COMMENTED** [review]
yes

**Review by DamieFC — APPROVED** [review]
yes

**Comment by Smart6502** [comment]
no

**Comment by Smart6502** [comment]
\# means you run the command as root bruh

**Comment by adamtherookie** [comment]
> # means you run the command as root bruh

Then add it bruh

**Comment by adamtherookie** [comment]
Done (:

**Comment by Smart6502** [comment]
That's gonna increase the size of the file
Sticking with `#` is better. Those letters you added are bloat.

**Comment by adamtherookie** [comment]
> That's gonna increase the size of the file
> Sticking with `#` is better. Those letters you added are bloat.

dude. duuuude. not everybody knows that `#` means to run as root (like me)

**Comment by PQCraft** [comment]
> > That's gonna increase the size of the file
> > Sticking with `#` is better. Those letters you added are bloat.
> 
> dude. duuuude. not everybody knows that `#` means to run as root (like me)

well you should learn it lol, everyone uses '#' to mean 'run as root'

**Comment by DamieFC** [comment]
> well you should learn it lol, everyone uses '#' to mean 'run as root'

Yeah, even ik and I use chromebook.

**Pull request closed without merging**
