### PR TITLE
fix: o4 is deprecated in clang

### PR DESCRIPTION
**Pull request by mTvare6**
image

### CODE REVIEW

**Comment by PQCraft** [comment]
e-z fix: use gcc

**Comment by Smart6502** [comment]
> image
> 

Hm, I will merge it once Im on my PC

**Comment by Smart6502** [comment]
> e-z fix: use gcc

Yes lol

**Comment by mTvare6** [comment]
@PQCraft doesn't mean you shouldn't fix stuff, gcc is slower and produces larger binaries than apple-clang

**Comment by Smart6502** [comment]
I wasn't aware about this

**Pull request merged**
